### ISSUE TITLE
ERD discussion

### ISSUE THREAD

**Issue by gbrlmrllo** [gbrlmrllo/chatops_builder_api#1]
This is my approach for a first app version, I would love to discuss it a bit so that we all have the same vision.

## ERD

![image](https://user-images.githubusercontent.com/3831984/80316638-409c7280-87d5-11ea-9a6c-fc71a5922dfd.png)

## How it will work.

* A user signs up
* The user creates an app
* The user can invite other users to the app
* The user can see the app credentials
* The user can create a `chatops_event`
* The user can integrate things to a `chatops_event` (**slack**, SendGrid, SMS)
* The user can organize its chatops_event by tags
* The user can see the triggered event list

Later we can detail a little more each model.

**Comment by luprz** [comment]
I like it ... although you're the idea owner, you have to guide us  :smile:

**Comment by gbrlmrllo** [comment]
Yes, I think the best thing to do is define what problem we want to solve with this app, it will add more value for people to contribute.

**Comment by gbrlmrllo** [comment]
I added this in the readme, I think it helps clarify what it is all about.

> **ChatOps Builder** is an app that allows you to centralize your notification events in order to monitor them and also be able to integrate them into applications such as Slack, SendGrid, Microsoft Teams, and many more.
